name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: randhir-kumar.in
          dist-id: E23JJOCV5LATWO
          invalidation: /*
